name: build-prod
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: teste.com
    needs: build
    steps:
      - name: Run a one-line script
        run: build prod!
